<?php

namespace Database\Seeders\User;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'employee_code' => 'EMP001',
                'name' => 'Admin System',
                'email' => 'admin@company.com',
                'phone' => '0900000001',
                'birthday' => '1990-01-01',
                'gender' => 'male',
                'department_id' => 1,
                'role_id' => 1,
                'position' => 'Administrator',
                'join_date' => '2020-01-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP002',
                'name' => 'HR Manager',
                'email' => 'hr@company.com',
                'phone' => '0900000002',
                'birthday' => '1991-02-10',
                'gender' => 'female',
                'department_id' => 2,
                'role_id' => 2,
                'position' => 'HR',
                'join_date' => '2021-01-10',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP003',
                'name' => 'Project Manager',
                'email' => 'pm@company.com',
                'phone' => '0900000003',
                'birthday' => '1989-05-12',
                'gender' => 'male',
                'department_id' => 3,
                'role_id' => 3,
                'position' => 'Project Manager',
                'join_date' => '2021-03-10',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP004',
                'name' => 'Tech Lead',
                'email' => 'techlead@company.com',
                'phone' => '0900000004',
                'birthday' => '1988-07-20',
                'gender' => 'male',
                'department_id' => 3,
                'role_id' => 4,
                'position' => 'Tech Lead',
                'join_date' => '2020-06-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP005',
                'name' => 'Backend Developer',
                'email' => 'backend@company.com',
                'phone' => '0900000005',
                'birthday' => '1995-03-15',
                'gender' => 'male',
                'department_id' => 3,
                'role_id' => 5,
                'position' => 'Backend Developer',
                'join_date' => '2022-01-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP006',
                'name' => 'Frontend Developer',
                'email' => 'frontend@company.com',
                'phone' => '0900000006',
                'birthday' => '1996-04-18',
                'gender' => 'female',
                'department_id' => 3,
                'role_id' => 6,
                'position' => 'Frontend Developer',
                'join_date' => '2022-02-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP007',
                'name' => 'QA Engineer',
                'email' => 'qa@company.com',
                'phone' => '0900000007',
                'birthday' => '1994-08-22',
                'gender' => 'female',
                'department_id' => 4,
                'role_id' => 7,
                'position' => 'QA',
                'join_date' => '2021-09-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP008',
                'name' => 'Tester',
                'email' => 'tester@company.com',
                'phone' => '0900000008',
                'birthday' => '1997-06-10',
                'gender' => 'male',
                'department_id' => 4,
                'role_id' => 8,
                'position' => 'Tester',
                'join_date' => '2023-01-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP009',
                'name' => 'UI/UX Designer',
                'email' => 'designer@company.com',
                'phone' => '0900000009',
                'birthday' => '1993-11-05',
                'gender' => 'female',
                'department_id' => 5,
                'role_id' => 9,
                'position' => 'Designer',
                'join_date' => '2021-07-15',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP010',
                'name' => 'DevOps Engineer',
                'email' => 'devops@company.com',
                'phone' => '0900000010',
                'birthday' => '1987-09-09',
                'gender' => 'male',
                'department_id' => 6,
                'role_id' => 10,
                'position' => 'DevOps',
                'join_date' => '2019-05-01',
                'status' => 'active',
                'password' => Hash::make('123456'),
                'email_verified_at' => now(),
                'password_changed_at' => now(),
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
